// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZlcT0X34u4yWhBfuz8o_p3vQJFKO_sNQ',
    appId: '1:641805303524:web:1b58bfd366909e6e2f36f1',
    messagingSenderId: '641805303524',
    projectId: 'turyn-viajes',
    authDomain: 'turyn-viajes.firebaseapp.com',
    storageBucket: 'turyn-viajes.appspot.com',
    measurementId: 'G-3MEBWET32D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarlqJjHnjT-leNM5GKlbshsdkhxQttHQ',
    appId: '1:641805303524:android:eb204c1fb916be092f36f1',
    messagingSenderId: '641805303524',
    projectId: 'turyn-viajes',
    storageBucket: 'turyn-viajes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMx-EhCuwRtB5kKi61yLmLP-08fBZsZPk',
    appId: '1:641805303524:ios:a58339af12d06b792f36f1',
    messagingSenderId: '641805303524',
    projectId: 'turyn-viajes',
    storageBucket: 'turyn-viajes.appspot.com',
    iosClientId: '641805303524-csusbq57h864fjg9g90mos6fg3505u50.apps.googleusercontent.com',
    iosBundleId: 'com.turynviajes.turynViajes',
  );
}
